tienda/urls.py
from django.contrib import admin
from django.urls import path,include

from tiendaApp.views import tienda, agregar_producto, eliminar_producto, restar_producto, limpiar_carrito,proceso_pago,webpay_redirect,procesar_compra,detalle_boleta

from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Tienda API",
      default_version='v1',
      description="API para la tienda",
      terms_of_service="https://www.tu-terminos-de-servicio.com/",
      contact=openapi.Contact(email="tu@email.com"),
      license=openapi.License(name="Tu Licencia"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', tienda, name="Tienda"),
    path('agregar/<int:producto_id>/', agregar_producto, name="Add"),
    path('eliminar/<int:producto_id>/', eliminar_producto, name="Del"),
    path('restar/<int:producto_id>/', restar_producto, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),
    path('api/tienda/v1/', include('rest_api_tienda.urls')),
    path('proceso_pago/', proceso_pago, name='pago'),
    path('webpay_redirect/', webpay_redirect, name='webpay_redirect'),
    path('procesar_compra/', procesar_compra, name='procesar_compra'),
    path('tienda/', tienda, name='tienda'),
    path('procesar_compra/boleta/<int:boleta_id>/', detalle_boleta, name='detalle_boleta'),
    # Agregar las siguientes líneas para la documentación con DRF-YASG
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

tiendaApp/models.py
from django.db import models

# Create your models here.
class Producto(models.Model):
    nombre = models.CharField(max_length=64)
    categoria = models.CharField(max_length=32)
    precio = models.IntegerField()

    def __str__(self):
        return f'{self.nombre} -> {self.precio}'

class Compra(models.Model):
    nombre = models.CharField(max_length=255)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=15)
    correo_electronico = models.EmailField()
    total = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_compra = models.DateTimeField(auto_now_add=True)
    

class DetalleCompra(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)



class Boleta(models.Model):
    numero = models.IntegerField()  # Número de boleta
    cliente = models.CharField(max_length=255)  # Cliente asociado a la boleta
    productos = models.ManyToManyField(Producto)  # Lista de productos incluidos en la boleta
    total = models.DecimalField(max_digits=10, decimal_places=2)  # Total de la boleta

    def imprimir_boleta(self):
        print("Boleta Número:", self.numero)
        print("Cliente:", self.cliente)
        print("Productos:")
        for producto in self.productos.all():
            print(f"- {producto.nombre}: {producto.precio}")
        print("Total:", self.total)

class DetalleBoleta(models.Model):
    boleta = models.ForeignKey(Boleta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

tiendaApp/forms.py
# En tu_app/forms.py
from django import forms

class CompraForm(forms.Form):
    nombre = forms.CharField(max_length=64, label="Nombre")
    direccion = forms.CharField(max_length=128, label="Dirección")
    telefono = forms.CharField(max_length=20, label="Teléfono")
    correo_electronico = forms.EmailField(label="Correo Electrónico")

tiendaApp/views.py
from django.shortcuts import render, HttpResponse, redirect,get_object_or_404
from tiendaApp.carrito import Carrito
from tiendaApp.models import Producto,Compra,DetalleCompra,Boleta
from .forms import CompraForm

def tienda(request):
    productos = Producto.objects.all()
    return render(request, "tienda.html", {'productos': productos})

def agregar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.agregar(producto)
    print(carrito.carrito)  # Imprime el contenido del carrito
    return redirect("tienda")

def eliminar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.eliminar(producto)
    return redirect("tienda")

def restar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.restar(producto)
    return redirect("tienda")

def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect("tienda")

def proceso_pago(request):
    carrito = Carrito(request)
    items_carrito = carrito.carrito.values()
    total_carrito = carrito.obtener_total_carrito()

    if request.method == 'POST':
        compra_form = CompraForm(request.POST)
        if compra_form.is_valid():
            # Guardar la información de la compra en la sesión
            request.session['compra'] = {
                'nombre': compra_form.cleaned_data['nombre'],
                'direccion': compra_form.cleaned_data['direccion'],
                'telefono': compra_form.cleaned_data['telefono'],
                'correo_electronico': compra_form.cleaned_data['correo_electronico'],
            }

            # Aquí puedes agregar la lógica de procesamiento de la compra si es necesario
            # ...

            # Redirigir a la página de confirmación o procesamiento de pago
            return redirect('detalle_boleta')
    else:
        compra_form = CompraForm()

    return render(request, "pago.html", {'items_carrito': items_carrito, 'total_carrito': total_carrito, 'compra_form': compra_form})

def webpay_redirect(request):
    # Lógica para la redirección a WebPay
    # ...

    return HttpResponse("Redirección a WebPay")

def procesar_compra(request):
    carrito = Carrito(request)
    total_carrito = carrito.obtener_total_carrito()

    if request.method == 'POST':
        compra_form = CompraForm(request.POST)
        if compra_form.is_valid():
            # Crear un objeto Compra y guardarlo en la base de datos
            nueva_compra = Compra(
                nombre=compra_form.cleaned_data['nombre'],
                direccion=compra_form.cleaned_data['direccion'],
                telefono=compra_form.cleaned_data['telefono'],
                correo_electronico=compra_form.cleaned_data['correo_electronico'],
                total=total_carrito  # Asegúrate de que este campo esté presente
            )
            nueva_compra.save()

            # Guardar los detalles de la compra en la base de datos
            for producto_id, info_producto in carrito.carrito.items():
                producto = Producto.objects.get(id=producto_id)
                detalle_compra = DetalleCompra(
                    compra=nueva_compra,
                    producto=producto,
                    cantidad=info_producto['cantidad'],
                    precio_unitario=producto.precio
                )
                detalle_compra.save()

            # Crear una nueva boleta asociada a la compra
            nueva_boleta = Boleta.objects.create(
                numero=nueva_compra.id,  # Usamos el ID de la compra como número de boleta
                cliente=nueva_compra.nombre,
                total=nueva_compra.total
            )
            nueva_boleta.productos.set([detalle.producto for detalle in nueva_compra.detallecompra_set.all()])

            # Limpiar el carrito después de la compra
            carrito.limpiar()

            # Redirigir a la página de confirmación o a donde desees
            return redirect('detalle_boleta', boleta_id=nueva_boleta.id)

    else:
        compra_form = CompraForm()

    return render(request, "pago.html", {'total_carrito': total_carrito, 'compra_form': compra_form})


def pagina_pago(request):
    # ... tu lógica actual ...

    if request.method == 'POST':
        compra_form = CompraForm(request.POST)
        if compra_form.is_valid():
            # Guardar la información de la compra en la sesión
            request.session['compra'] = {
                'nombre': compra_form.cleaned_data['nombre'],
                'direccion': compra_form.cleaned_data['direccion'],
                'telefono': compra_form.cleaned_data['telefono'],
                'correo_electronico': compra_form.cleaned_data['correo_electronico'],
            }

            # Redirigir a la página de confirmación o procesamiento de pago
            return redirect('pagina_confirmacion_pago')
    else:
        compra_form = CompraForm()

    # ... tu lógica actual ...

    return render(request, 'tu_app/pagina_pago.html', {
        'compra_form': compra_form,
        # ... otros contextos ...
    })

def detalle_boleta(request, boleta_id):
    boleta = get_object_or_404(Boleta, id=boleta_id)
    return render(request, 'boleta.html', {'boleta': boleta})

tiendaApp/templates/boleta.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Boleta</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        .boleta {
            border: 1px solid #ccc;
            padding: 20px;
            max-width: 600px;
            margin: 0 auto;
        }

        h1 {
            text-align: center;
        }

        .cliente-info {
            margin-bottom: 20px;
        }

        .productos {
            margin-top: 20px;
        }

        .total {
            margin-top: 20px;
            text-align: right;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="boleta">
        <h1>Boleta Número: {{ boleta.numero }}</h1>

        <!-- Enlace para volver a la Tienda -->
        <a href="{% url 'tienda' %}">Volver a la Tienda</a>

        <div class="cliente-info">
            <p><strong>Cliente:</strong> {{ boleta.cliente }}</p>
        </div>

        <div class="productos">
            <h2>Productos:</h2>
            <ul>
                {% for producto in boleta.productos.all %}
                    <li>{{ producto.nombre }} - {{ producto.precio }}</li>
                {% endfor %}
            </ul>
        </div>

        <div class="total">
            <p><strong>Total:</strong> {{ boleta.total }}</p>
        </div>
    </div>
</body>
</html>

tiendaApp/templates/carrito.html
<div class="alert alert-primary alert-carrito" role="alert">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="row" colspan="3" class="text-center">CARRITO</th>
            </tr>
            <tr>
                <th scope="col">NOMBRE</th>
                <th scope="col">PRECIO</th>
                <th scope="col">CANTIDAD</th>
            </tr>
        </thead>
        <tbody>
            {% if request.session.carrito.items %}
            {% for key, value in request.session.carrito.items %}
            <tr>
                <td>{{ value.nombre }}</td>
                <td>${{ value.acumulado }}</td>
                <td>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <a href="{% url 'Sub' value.producto_id %}" class="btn btn-dark">-</a>
                        </div>
                        <input type="text" class="form-control text-center" value="{{ value.cantidad }}" readonly>
                        <div class="input-group-append">
                            <a href="{% url 'Add' value.producto_id %}" class="btn btn-dark">+</a>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center"> Sin Productos </div>
                </td>
            </tr>
            {% endif %}
            <tr>
                <th scope="row">Total:</th>
                <td colspan="2">$ {{ total_carrito }}</td>
            </tr>
        </tbody>
    </table>
    <hr>
</div>
<div class="row text-center">
    <div class="col-6"><a href="{% url 'CLS' %}" class="btn btn-danger">Limpiar</a></div>
    <div class="col-6"><a href="{% url 'pago' %}" class="btn btn-success">Comprar</a></div>
</div>

tiendaApp/templates/pago.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Página de Pago</title>
    <!-- Bootstrap CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Otros estilos o scripts necesarios -->
</head>
<body>
    <div class="container my-4">
        <h1 class="display-4">Resumen de Compra</h1>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Producto</th>
                    <th scope="col">Precio Unitario</th>
                    <th scope="col">Cantidad</th>
                </tr>
            </thead>
            <tbody>
                {% for key, value in request.session.carrito.items %}
                <tr>
                    <td>{{ value.nombre }}</td>
                    <td>{{ value.cantidad }}</td>
                    <td>${{ value.acumulado }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <p>Total: ${{ total_carrito }}</p>

        <!-- Formulario para los datos de compra -->
        <form id="compraForm" method="post" action="{% url 'procesar_compra' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_nombre" class="form-label">Nombre</label>
                <input type="text" class="form-control" id="id_nombre" name="nombre" required>
            </div>
            <div class="mb-3">
                <label for="id_direccion" class="form-label">Dirección</label>
                <input type="text" class="form-control" id="id_direccion" name="direccion" required>
            </div>
            <div class="mb-3">
                <label for="id_telefono" class="form-label">Teléfono</label>
                <input type="text" class="form-control" id="id_telefono" name="telefono" required>
            </div>
            <div class="mb-3">
                <label for="id_correo_electronico" class="form-label">Correo Electrónico</label>
                <input type="email" class="form-control" id="id_correo_electronico" name="correo_electronico" required>
            </div>
            <button type="submit" class="btn btn-primary">Guardar Datos y Pagar</button>
        </form>
    </div>

    <!-- Bootstrap JS y jQuery u otros scripts necesarios -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Otros scripts si es necesario -->
</body>
</html>

tiendaApp/templates/tienda.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Bienvenido a la Tienda</title>
    <!-- Bootstrap CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Styles -->
    <link href="{% static 'css/estilos.css' %}" rel="stylesheet">
</head>
<body>
    <!-- Banner pequeño -->
    <div class="container-fluid bg-dark">
        <div class="row">
            <div class="col-12 text-center">
                <img src="{% static 'img/imagen1.png' %}" class="img-fluid" alt="Banner">
            </div>
        </div>
    </div>

    <!-- Resto de tu contenido -->
    <div class="container my-4">
        <div class="row justify-content-center">
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="row" style="padding: 10px 0;">
                    <div class="col-12">
                        <div class="row">
                            {% for producto in productos %}
                            <div class="col-6">
                                <div class="card card-producto">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ producto.nombre }}</h5>
                                        <p class="card-text">{{ producto.categoria }}</p>
                                        <p class="card-text">{{ producto.precio }}</p>
                                        <a href="{% url 'Add' producto.id %}" class="btn btn-primary">Agregar al carrito</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                {% include "carrito.html" %}
            </div>
        </div>
    </div>

    <!-- Bootstrap JS y jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
    
</body>
</html>